//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentInfo
    {
        public string AgentId { get; set; }
        public string AgentName { get; set; }
        public string GroupId { get; set; }
        public string Sex { get; set; }
        public string Password { get; set; }
        public string Role { get; set; }
        public string IP { get; set; }
    }
}
