//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentStatusLog
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> StatisticDate { get; set; }
        public string Status { get; set; }
        public string PhoneNo { get; set; }
        public string GroupNo { get; set; }
        public string AgentNo { get; set; }
        public Nullable<int> StatisticTime { get; set; }
        public string CallID { get; set; }
        public string CallerID { get; set; }
        public string CalleeID { get; set; }
        public string CallDir { get; set; }
        public string CallType { get; set; }
        public string MonitedAgentPhoneNo { get; set; }
        public string MonitedAgentNo { get; set; }
        public string CallSrc { get; set; }
        public Nullable<int> parkcause { get; set; }
    }
}
