//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_PersonContact
    {
        public int iID { get; set; }
        public string vPersonalID { get; set; }
        public string vCUSTOMCODE { get; set; }
        public string nNCUSTOMNAME { get; set; }
        public string nCUSTENGNAME { get; set; }
        public string vPHONE1 { get; set; }
        public string vPHONE2 { get; set; }
        public string vCELLPHONE { get; set; }
        public string nEMAIL { get; set; }
        public string cFLAG { get; set; }
        public string dtBIRTHDAY { get; set; }
        public string nMICROBOLOG { get; set; }
        public string vQQ { get; set; }
        public string mMSN { get; set; }
        public string nDUTY { get; set; }
        public string NCOMPANY { get; set; }
        public string nHOBY { get; set; }
        public string nADDRESS { get; set; }
        public string vNUMBER { get; set; }
        public string nMEMO { get; set; }
        public string nFiled1 { get; set; }
        public string nFiled2 { get; set; }
        public string nFiled3 { get; set; }
        public Nullable<System.DateTime> dtFiled4 { get; set; }
        public Nullable<System.DateTime> dtFiled5 { get; set; }
        public Nullable<int> iFiled6 { get; set; }
        public Nullable<int> iFiled7 { get; set; }
        public Nullable<int> iFiled8 { get; set; }
        public Nullable<double> fFiled9 { get; set; }
        public Nullable<double> fFiled10 { get; set; }
        public Nullable<System.DateTime> dtInsTime { get; set; }
        public string vInsUser { get; set; }
        public Nullable<System.DateTime> dtUpdTime { get; set; }
        public string vUpdUser { get; set; }
    }
}
