//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invert_Main_Preview
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> S_Date { get; set; }
        public Nullable<System.DateTime> E_Date { get; set; }
        public string Description { get; set; }
        public string Title { get; set; }
        public string Process { get; set; }
        public Nullable<int> A_Count { get; set; }
        public Nullable<int> Q_Count { get; set; }
        public string Owner { get; set; }
        public Nullable<int> PageCount { get; set; }
        public string IsDesign { get; set; }
        public string MainCode { get; set; }
        public string ViceTitle { get; set; }
    }
}
