//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lxrbyzd
    {
        public int ID { get; set; }
        public string TableName { get; set; }
        public string Byzd1 { get; set; }
        public string Byzd2 { get; set; }
        public string Byzd3 { get; set; }
        public string Byzd4 { get; set; }
        public string Byzd5 { get; set; }
        public string Byzd6 { get; set; }
        public string Byzd7 { get; set; }
        public string Byzd8 { get; set; }
        public string Byzd9 { get; set; }
        public string Byzd10 { get; set; }
    }
}
