//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_CKGL
    {
        public int IID { get; set; }
        public string CpCode { get; set; }
        public string CpName { get; set; }
        public Nullable<int> CkSl { get; set; }
        public string CpDw { get; set; }
        public Nullable<System.DateTime> LyTime { get; set; }
        public string LyrName { get; set; }
        public string CkrName { get; set; }
        public string CkWz { get; set; }
        public string CkSm { get; set; }
        public Nullable<int> cIsRemover { get; set; }
        public Nullable<int> biaoshi1 { get; set; }
        public string Cplx { get; set; }
    }
}
