//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_FWXXMX
    {
        public int iID { get; set; }
        public string vFWBH { get; set; }
        public string vFWDX { get; set; }
        public string vHTBH { get; set; }
        public string vDXBH { get; set; }
        public string vDXBS { get; set; }
        public Nullable<System.DateTime> dJDSJ { get; set; }
        public string nKHLXR { get; set; }
        public string vLXDH { get; set; }
        public string nFWEY { get; set; }
        public string vFWLX { get; set; }
        public string nFWDZ { get; set; }
        public string vFWFS { get; set; }
        public Nullable<System.DateTime> iPGSJ { get; set; }
        public string vFWLB { get; set; }
        public string vHXFWBH { get; set; }
        public string vSCFWBH { get; set; }
        public string nMemo { get; set; }
        public string vInsUser { get; set; }
        public Nullable<System.DateTime> dInsTime { get; set; }
        public string vUpdUser { get; set; }
        public Nullable<System.DateTime> dUpdTime { get; set; }
        public string cIsRemove { get; set; }
        public string vFWNR { get; set; }
        public Nullable<System.DateTime> dYJPGSJ { get; set; }
        public string nFWGCS { get; set; }
        public string WorkRNGY { get; set; }
        public string nPgzt { get; set; }
    }
}
