//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_GYS
    {
        public int iGYSID { get; set; }
        public string vGYSCode { get; set; }
        public string nGYSMC { get; set; }
        public string vQY { get; set; }
        public string vCS { get; set; }
        public string nDZ1 { get; set; }
        public string nDZ2 { get; set; }
        public string vDH1 { get; set; }
        public string vDH2 { get; set; }
        public string vGYSLB { get; set; }
        public string vGYSJB { get; set; }
        public string vSSXS { get; set; }
        public string vSSHY { get; set; }
        public string vGYSGM { get; set; }
        public string cIsRemove { get; set; }
        public string nMemo { get; set; }
        public Nullable<System.DateTime> dInsTime { get; set; }
        public string vInsUser { get; set; }
        public Nullable<System.DateTime> dUpdTime { get; set; }
        public string vUpdUser { get; set; }
    }
}
