//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_JXS
    {
        public int iJXSID { get; set; }
        public string vJXSCode { get; set; }
        public string nJXSMC { get; set; }
        public string vQY { get; set; }
        public string vCS { get; set; }
        public string nJXSDZ1 { get; set; }
        public string nJXSDZ2 { get; set; }
        public string vJXSDH1 { get; set; }
        public string vJXSDH2 { get; set; }
        public string vJXSLB { get; set; }
        public string vJXSJB { get; set; }
        public string vSSXS { get; set; }
        public string vSSHY { get; set; }
        public string vJXSGM { get; set; }
        public string cIsRemove { get; set; }
        public string nMemo { get; set; }
        public Nullable<System.DateTime> dInsTime { get; set; }
        public string vInsUser { get; set; }
        public Nullable<System.DateTime> dUpdTime { get; set; }
        public string vUpdUser { get; set; }
    }
}
