//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_KHLLJL
    {
        public int LljlID { get; set; }
        public string vKHCode { get; set; }
        public string vYGCode { get; set; }
        public string LljlGSName { get; set; }
        public string LljlType { get; set; }
        public Nullable<System.DateTime> LljlTime { get; set; }
        public string LljlZT { get; set; }
        public string LljlRN { get; set; }
        public string LljlJH { get; set; }
        public Nullable<System.DateTime> LljlTimeTX { get; set; }
        public string LljlName { get; set; }
        public Nullable<int> LljlZTai { get; set; }
    }
}
