//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_KHHTCP
    {
        public int iID { get; set; }
        public string vCPCode { get; set; }
        public string vKHHTCode { get; set; }
        public Nullable<decimal> dZKL { get; set; }
        public Nullable<decimal> mZKJ { get; set; }
        public Nullable<int> iCPSL { get; set; }
        public Nullable<decimal> mZKHZJ { get; set; }
        public string nMemo { get; set; }
        public string vInsUser { get; set; }
        public Nullable<System.DateTime> dInsTime { get; set; }
        public string vUpdUser { get; set; }
        public Nullable<System.DateTime> dUpdTime { get; set; }
        public string cIsRemove { get; set; }
    }
}
