//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_KHBZ
    {
        public int BZID { get; set; }
        public string vKHCode { get; set; }
        public string BZTitle { get; set; }
        public string BZContent { get; set; }
        public Nullable<System.DateTime> AlertTime { get; set; }
        public Nullable<System.DateTime> dInsTime { get; set; }
        public string vInsUser { get; set; }
        public Nullable<System.DateTime> dUpdTime { get; set; }
        public string vUpdUser { get; set; }
    }
}
