//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Publish_Project_Detail
    {
        public int iID { get; set; }
        public Nullable<int> MainID { get; set; }
        public string VersionNO { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
        public string UpdateContent { get; set; }
        public string nMemo { get; set; }
        public Nullable<int> iFiled1 { get; set; }
        public Nullable<int> iFiled2 { get; set; }
        public Nullable<int> iFiled3 { get; set; }
        public string nFiled4 { get; set; }
        public string nFiled5 { get; set; }
        public string nFiled6 { get; set; }
        public string vField7 { get; set; }
        public string vFiled8 { get; set; }
        public Nullable<System.DateTime> dtField9 { get; set; }
        public Nullable<System.DateTime> dtField10 { get; set; }
        public string vInsUser { get; set; }
        public Nullable<System.DateTime> dtInsTime { get; set; }
        public string vUpdUser { get; set; }
        public Nullable<System.DateTime> dtUpdTime { get; set; }
    }
}
