//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_SFZLXR
    {
        public int iLXRID { get; set; }
        public string vLXRCode { get; set; }
        public string nLXRMC { get; set; }
        public string Sex { get; set; }
        public string Birthday { get; set; }
        public string Phone { get; set; }
        public string CellPhone { get; set; }
        public string Email { get; set; }
        public string Zone { get; set; }
        public string Census { get; set; }
        public string Background { get; set; }
        public string Revenue { get; set; }
        public string Marriage { get; set; }
        public string Industry { get; set; }
        public string WorkType { get; set; }
        public string Profession { get; set; }
        public string QQ { get; set; }
        public string LXRHobby { get; set; }
        public string iStatus { get; set; }
        public string iAddress { get; set; }
        public string Remark { get; set; }
        public string Recommended { get; set; }
        public string dInsUser { get; set; }
        public Nullable<System.DateTime> dInsTime { get; set; }
        public string vUpdUser { get; set; }
        public Nullable<System.DateTime> dUpdTime { get; set; }
        public string cSFTGSH { get; set; }
        public string cIsRemove { get; set; }
        public string nByzd1 { get; set; }
        public string nByzd2 { get; set; }
        public string nByzd3 { get; set; }
        public string nByzd4 { get; set; }
        public string nByzd5 { get; set; }
        public string nByzd6 { get; set; }
        public string nByzd7 { get; set; }
        public string nByzd8 { get; set; }
        public string nByzd9 { get; set; }
        public string nByzd10 { get; set; }
        public string iFlag { get; set; }
    }
}
