//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Q_Entity
    {
        public int ID { get; set; }
        public Nullable<int> M_ID { get; set; }
        public string QTCode { get; set; }
        public Nullable<int> OrderNo { get; set; }
        public string QText { get; set; }
        public Nullable<int> PageNo { get; set; }
        public string IsRequired { get; set; }
        public string Q_Code { get; set; }
        public string vFlag { get; set; }
    }
}
