//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class QC_Answer
    {
        public Nullable<int> Q_ID { get; set; }
        public string Answer { get; set; }
        public string AnswerID { get; set; }
        public string ControlID { get; set; }
        public int id { get; set; }
    }
}
