//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_Config
    {
        public string vCfgType { get; set; }
        public string vCfgKey { get; set; }
        public Nullable<int> iCfgSortNo { get; set; }
        public string vCfgValue01 { get; set; }
        public string vCfgValue02 { get; set; }
        public string vCfgValue03 { get; set; }
        public string vCfgValue04 { get; set; }
        public string vCfgValue05 { get; set; }
        public string vCfgValue06 { get; set; }
        public string vCfgValue07 { get; set; }
        public string vCfgValue08 { get; set; }
        public string vCfgValue09 { get; set; }
        public string vCfgValue10 { get; set; }
    }
}
