//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ATTACH
    {
        public System.Guid uGuid { get; set; }
        public string uObjectId { get; set; }
        public string nFileName { get; set; }
        public string nLinkUrl { get; set; }
        public string nFilePath { get; set; }
        public Nullable<int> iSortNo { get; set; }
        public string cIsRemove { get; set; }
        public Nullable<System.DateTime> dInsTime { get; set; }
        public string vInsUser { get; set; }
        public Nullable<System.DateTime> dUpdTime { get; set; }
        public string vUpdUser { get; set; }
    }
}
