//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BLACK_LIST
    {
        public int AUTO_ID { get; set; }
        public string PHONE_NO { get; set; }
        public string NOTES { get; set; }
        public string EXT_FIELD1 { get; set; }
        public string EXT_FIELD2 { get; set; }
        public string DELETE_FLG { get; set; }
        public string CREATE_USER { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string UPDATE_USER { get; set; }
        public System.DateTime UPDATE_TIME { get; set; }
    }
}
