//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_FORM
    {
        public string Field_Name { get; set; }
        public string Display_Text { get; set; }
        public byte Display_Type { get; set; }
        public byte Sort_No { get; set; }
        public string Create_User { get; set; }
        public System.DateTime Create_Time { get; set; }
        public string Update_User { get; set; }
        public System.DateTime Update_Time { get; set; }
        public Nullable<byte> Use_Flag { get; set; }
        public Nullable<byte> Pop_Out_Flag { get; set; }
        public int id { get; set; }
    }
}
