//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_GYSFH
    {
        public int iID { get; set; }
        public string vGYSCode { get; set; }
        public string vSHDXBS { get; set; }
        public string vSHDXCode { get; set; }
        public string vCPCode { get; set; }
        public string vSL { get; set; }
        public Nullable<int> iFHRQ { get; set; }
        public Nullable<int> iQSRQ { get; set; }
        public string vQSR { get; set; }
        public string nFJURL { get; set; }
        public string vKDDH { get; set; }
        public string vKDGS { get; set; }
        public string cSFRK { get; set; }
        public string nMemo { get; set; }
        public string vInsUser { get; set; }
        public Nullable<System.DateTime> dInsTime { get; set; }
        public string vUpdUser { get; set; }
        public Nullable<System.DateTime> dUpdTime { get; set; }
        public string cIsRemove { get; set; }
    }
}
