//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ImagePath
    {
        public int ID { get; set; }
        public string ImageName { get; set; }
        public string ImageType { get; set; }
        public string ImagePath { get; set; }
        public Nullable<long> IsUse { get; set; }
        public Nullable<System.DateTime> dtInsTime { get; set; }
        public Nullable<System.DateTime> dtUpdTime { get; set; }
    }
}
