//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_InspectionTask
    {
        public int iITaskID { get; set; }
        public string vITaskCode { get; set; }
        public string nTheme { get; set; }
        public Nullable<System.DateTime> dtStratTime { get; set; }
        public Nullable<System.DateTime> dtEndTime { get; set; }
        public string vStatus { get; set; }
        public string vTemplate { get; set; }
        public string cIsRemove { get; set; }
        public string nMemo { get; set; }
        public string vInsUser { get; set; }
        public Nullable<System.DateTime> dInsTime { get; set; }
        public string vUpdUser { get; set; }
        public Nullable<System.DateTime> dUpdTime { get; set; }
        public string vField01 { get; set; }
        public string vField02 { get; set; }
        public string vField03 { get; set; }
        public string nField04 { get; set; }
        public string nField05 { get; set; }
        public string nField06 { get; set; }
        public Nullable<int> iField07 { get; set; }
        public Nullable<int> iField08 { get; set; }
        public Nullable<System.DateTime> dField09 { get; set; }
        public Nullable<System.DateTime> dField10 { get; set; }
    }
}
