//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_MAIL
    {
        public int MAIL_ID { get; set; }
        public string PLAN_ID { get; set; }
        public string MAIL_STATUS { get; set; }
        public string MAIL_SERVER_TYPE { get; set; }
        public string MAIL_FROM_PWD { get; set; }
        public string MAIL_NOTES_FILE { get; set; }
        public string SEND_TO { get; set; }
        public string MAIL_FROM { get; set; }
        public string MAIL_CC { get; set; }
        public string MAIL_BCC { get; set; }
        public string MAIL_TYPE { get; set; }
        public string MAIL_TITLE { get; set; }
        public string MAIL_CONTENT { get; set; }
        public Nullable<System.DateTime> SEND_TIME { get; set; }
        public string FAIL_REASON { get; set; }
        public string DELETE_FLG { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_USER { get; set; }
        public Nullable<int> UPDATE_COUNT { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string UPDATE_USER { get; set; }
        public Nullable<int> DISP_FLG { get; set; }
        public string vFlag { get; set; }
        public string vFlag_Tick { get; set; }
    }
}
