//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_MAIL_ATTACHMENT
    {
        public int ATTACHMENT_ID { get; set; }
        public string TEMPLATE_ID { get; set; }
        public Nullable<int> MAIL_ID { get; set; }
        public string ATTACHMENT_KBN { get; set; }
        public string ATTACHMENT_NAME { get; set; }
        public string ATTACHMENT_PATH { get; set; }
        public int ATTACHMENT_SIZE { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_USER { get; set; }
        public Nullable<int> UPDATE_COUNT { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string UPDATE_USER { get; set; }
    }
}
