//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Msg
    {
        public int ID { get; set; }
        public string SendMan { get; set; }
        public Nullable<int> SequenceID { get; set; }
        public string SrcID { get; set; }
        public string ServiceID { get; set; }
        public Nullable<bool> NeedStatus { get; set; }
        public string DestMobiles { get; set; }
        public Nullable<int> DestCount { get; set; }
        public Nullable<bool> SendNow { get; set; }
        public Nullable<System.DateTime> AtTime { get; set; }
        public string MsgContent { get; set; }
        public string MsgId { get; set; }
        public string Result { get; set; }
    }
}
