//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PAGE
    {
        public string vPageCode { get; set; }
        public string nPageTitle { get; set; }
        public string vPageName { get; set; }
        public string vParentPageCode { get; set; }
        public string cPageType { get; set; }
        public Nullable<int> iSortNo { get; set; }
        public string vLinkUrl { get; set; }
        public string vHtml { get; set; }
        public string cIsUse { get; set; }
        public string nMemo { get; set; }
        public string nExpand01 { get; set; }
        public string nExpand02 { get; set; }
        public string nExpand03 { get; set; }
        public string nExpand04 { get; set; }
        public string nExpand05 { get; set; }
        public Nullable<System.DateTime> dCreateTime { get; set; }
        public Nullable<System.Guid> uCreadeUser { get; set; }
        public Nullable<System.DateTime> dUpdateTime { get; set; }
        public Nullable<System.Guid> uUpdateUser { get; set; }
    }
}
