//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_REFUND
    {
        public int ID { get; set; }
        public string RF_CODE { get; set; }
        public string RF_REASON { get; set; }
        public Nullable<int> RF_OT_ID { get; set; }
        public byte RF_TYPE { get; set; }
        public decimal RF_MONEY { get; set; }
        public string RF_MEMO { get; set; }
        public string INSERT_USER { get; set; }
        public Nullable<System.DateTime> INSERT_DATETIME { get; set; }
        public string RF_GUY { get; set; }
        public System.DateTime RF_DATETIME { get; set; }
        public byte RF_STATUS { get; set; }
        public Nullable<System.DateTime> RF_APP_DATETIME { get; set; }
        public string RF_APP_GUY { get; set; }
    }
}
