//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_RECORD_DETAIL
    {
        public decimal REC_ID { get; set; }
        public string CTI_ID { get; set; }
        public string SERVER_IP { get; set; }
        public string CHANNEL_NO { get; set; }
        public string AGENT_ID { get; set; }
        public string AGENT_NAME { get; set; }
        public string CALLER { get; set; }
        public string CALLEE { get; set; }
        public Nullable<System.DateTime> BEGIN_TIME { get; set; }
        public Nullable<System.DateTime> END_TIME { get; set; }
        public string IS_INCOME { get; set; }
        public string IS_NOANSWER { get; set; }
        public string REC_FILE_PATH { get; set; }
    }
}
