//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ROLE
    {
        public System.Guid uRoleId { get; set; }
        public string vRoleCode { get; set; }
        public string nRoleNm { get; set; }
        public string cIsBase { get; set; }
        public string vParentCode { get; set; }
        public string cIsApprove { get; set; }
        public string nMemo { get; set; }
        public string cIsRemove { get; set; }
        public Nullable<System.DateTime> dInsTime { get; set; }
        public string vInsUser { get; set; }
        public Nullable<System.DateTime> dUpdTime { get; set; }
        public string vUpdUser { get; set; }
        public string nField01 { get; set; }
        public string nField02 { get; set; }
        public string nField03 { get; set; }
        public string nField04 { get; set; }
        public string nField05 { get; set; }
        public string nField06 { get; set; }
        public string nField07 { get; set; }
        public string nField08 { get; set; }
        public string nField09 { get; set; }
        public string nField10 { get; set; }
    }
}
