//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Ticket
    {
        public int iID { get; set; }
        public string vTicketCode { get; set; }
        public string vContactCode { get; set; }
        public string nContact { get; set; }
        public string vHeadCode { get; set; }
        public Nullable<System.DateTime> dtTime { get; set; }
        public Nullable<System.DateTime> dtEstimattime { get; set; }
        public Nullable<System.DateTime> dtRealtime { get; set; }
        public string nTitle { get; set; }
        public string nContent { get; set; }
        public Nullable<int> iFlag { get; set; }
        public string vPhone { get; set; }
        public string vMail { get; set; }
        public Nullable<int> iType { get; set; }
        public string nMemo { get; set; }
        public string nFiled1 { get; set; }
        public string nFiled2 { get; set; }
        public string nFiled3 { get; set; }
        public Nullable<System.DateTime> dtFiled4 { get; set; }
        public Nullable<System.DateTime> dtFiled5 { get; set; }
        public Nullable<int> iFiled6 { get; set; }
        public Nullable<int> iFiled7 { get; set; }
        public Nullable<int> iFiled8 { get; set; }
        public Nullable<double> fFiled9 { get; set; }
        public Nullable<double> fFiled10 { get; set; }
        public Nullable<System.DateTime> dtInsTime { get; set; }
        public string vInsUser { get; set; }
        public Nullable<System.DateTime> dtUpdTime { get; set; }
        public string vUpdUser { get; set; }
        public string cIsRemove { get; set; }
        public string vTicType { get; set; }
    }
}
