//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_YJZCGL
    {
        public int ZCID { get; set; }
        public string ZCModel { get; set; }
        public string ZCStype { get; set; }
        public string ZCCode { get; set; }
        public string ZCPZ { get; set; }
        public string ZCsyr { get; set; }
        public string ZClyrName { get; set; }
        public Nullable<System.DateTime> ZClyTime { get; set; }
        public Nullable<System.DateTime> ZCghTime { get; set; }
        public string ZCghlsr { get; set; }
        public Nullable<int> ZCZtai { get; set; }
    }
}
