//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task_Dial_Cus
    {
        public int iID { get; set; }
        public int iMainID { get; set; }
        public string vCusCode { get; set; }
        public string vAgentCode { get; set; }
        public string CusZD1 { get; set; }
        public string CusZD2 { get; set; }
        public string CusZD3 { get; set; }
        public string CusZD4 { get; set; }
        public string CusZD5 { get; set; }
        public Nullable<System.DateTime> CusZD6 { get; set; }
        public Nullable<System.DateTime> CusZD7 { get; set; }
        public string CusZD8 { get; set; }
        public string CusZD9 { get; set; }
        public string CusZD10 { get; set; }
        public Nullable<System.DateTime> dtInsTime { get; set; }
        public string vInsUser { get; set; }
        public Nullable<System.DateTime> dtUpdTime { get; set; }
        public string vUpdUser { get; set; }
    }
}
