//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task_Dial_Temp
    {
        public int iID { get; set; }
        public Nullable<System.DateTime> DialZD1 { get; set; }
        public Nullable<System.DateTime> DialZD2 { get; set; }
        public string DialZD3 { get; set; }
        public string DialZD4 { get; set; }
        public string DialZD5 { get; set; }
        public string DialZD6 { get; set; }
        public string DialZD7 { get; set; }
        public string DialZD8 { get; set; }
        public string DialZD9 { get; set; }
        public string DialZD10 { get; set; }
        public Nullable<System.DateTime> DialZD11 { get; set; }
        public Nullable<System.DateTime> DialZD12 { get; set; }
        public string DialZD13 { get; set; }
        public string DialZD14 { get; set; }
        public string DialZD15 { get; set; }
        public Nullable<System.DateTime> dtInsTime { get; set; }
        public string vInsUser { get; set; }
        public Nullable<System.DateTime> dtUpdTime { get; set; }
        public string vUpdUser { get; set; }
    }
}
