//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrunkStatistic
    {
        public int ID { get; set; }
        public string TrunkDN { get; set; }
        public string TrunkGroupID { get; set; }
        public Nullable<System.DateTime> StatisticDate { get; set; }
        public Nullable<double> IdleTime { get; set; }
        public Nullable<int> IdleCount { get; set; }
        public Nullable<double> RingTime { get; set; }
        public Nullable<int> RingCount { get; set; }
        public Nullable<double> DialingTime { get; set; }
        public Nullable<int> DialingCount { get; set; }
        public Nullable<double> ConnectInTime { get; set; }
        public Nullable<int> ConnectInCount { get; set; }
        public Nullable<double> ConnectOutTime { get; set; }
        public Nullable<int> ConnectOutCount { get; set; }
        public Nullable<int> OutDialFailCount { get; set; }
        public Nullable<int> NoPickupCount { get; set; }
        public Nullable<double> CrossConnectInTime { get; set; }
        public Nullable<int> CrossConnectInCount { get; set; }
        public Nullable<double> CrossConnectOutTime { get; set; }
        public Nullable<int> CrossConnectOutCount { get; set; }
        public Nullable<double> TrunkConnectInTime { get; set; }
        public Nullable<int> TrunkConnectInCount { get; set; }
        public Nullable<double> TrunkConnectOutTime { get; set; }
        public Nullable<int> TrunkConnectOutCount { get; set; }
    }
}
