//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VDNLog
    {
        public int ID { get; set; }
        public string VDNID { get; set; }
        public Nullable<System.DateTime> StatisticDate { get; set; }
        public string CallID { get; set; }
        public string CallType { get; set; }
        public string CallingID { get; set; }
        public string CalledID { get; set; }
        public string ExtDevice { get; set; }
        public Nullable<double> AnswerTime { get; set; }
        public Nullable<double> TalkTime { get; set; }
        public string Cause { get; set; }
        public Nullable<double> QueuedTime { get; set; }
        public string GlobalCallID { get; set; }
    }
}
