//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer_Entity
    {
        public int AE_ID { get; set; }
        public string IP { get; set; }
        public Nullable<int> M_ID { get; set; }
        public Nullable<int> A_ID { get; set; }
        public string IsFinished { get; set; }
        public Nullable<System.DateTime> AnswerDate { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string vFlag { get; set; }
    }
}
