//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_Business
    {
        public int iID { get; set; }
        public string vBusinessID { get; set; }
        public string vInsUser { get; set; }
        public Nullable<System.DateTime> dtInsDate { get; set; }
        public string vCusCode { get; set; }
        public string vIndustry { get; set; }
        public string vBusContent { get; set; }
        public string vBusFrom { get; set; }
        public string vBusProcess { get; set; }
        public Nullable<int> mAmount { get; set; }
        public Nullable<System.DateTime> dtResult { get; set; }
        public string vDistribution { get; set; }
        public string vSalesCode { get; set; }
        public string vUpdUser { get; set; }
        public Nullable<System.DateTime> dtUpdDate { get; set; }
        public string cIsRemove { get; set; }
    }
}
