//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ibDeviceGroupStatistic
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> StatisticDate { get; set; }
        public Nullable<int> StatisticHour { get; set; }
        public string GroupNo { get; set; }
        public Nullable<int> AnswerCalls { get; set; }
        public Nullable<double> TotalAnswerTime { get; set; }
        public Nullable<double> MaxAnswerTime { get; set; }
        public Nullable<double> TotalInTalkingTime { get; set; }
        public Nullable<double> MaxInTalkingTime { get; set; }
        public Nullable<double> TotalIdleTime { get; set; }
        public Nullable<double> MaxIdleTime { get; set; }
        public Nullable<int> TotalIdleTimes { get; set; }
        public Nullable<int> TotalInTransferTimes { get; set; }
        public Nullable<int> TotalInTransferSuccessTimes { get; set; }
        public Nullable<int> TotalDialTimes { get; set; }
        public Nullable<double> TotalDialTime { get; set; }
        public Nullable<int> TotalDialSuccessTimes { get; set; }
        public Nullable<double> MaxOutTalkingTime { get; set; }
        public Nullable<double> TotalOutTalkingTime { get; set; }
        public Nullable<int> TotalOutTransferTimes { get; set; }
        public Nullable<int> TotalOutTransferSuccessTimes { get; set; }
    }
}
