//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_GYSBF_HY
    {
        public int iBFId { get; set; }
        public string vBFCode { get; set; }
        public string vGYSCode { get; set; }
        public Nullable<int> iBFRQ { get; set; }
        public string vBFLX { get; set; }
        public string vLXRCode { get; set; }
        public string nBFNR { get; set; }
        public string cZCBF { get; set; }
        public string nXCBFNR { get; set; }
        public Nullable<int> iXCBFRQ { get; set; }
        public string nFJURL { get; set; }
        public string cQQHQH { get; set; }
        public string nMemo { get; set; }
        public string vInsUser { get; set; }
        public Nullable<System.DateTime> dInsTime { get; set; }
        public string vUpdUser { get; set; }
        public Nullable<System.DateTime> dUpdTime { get; set; }
        public string cIsRemove { get; set; }
    }
}
