//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_GYSHT
    {
        public int iHTID { get; set; }
        public string vHTCode { get; set; }
        public string vGYSCode { get; set; }
        public string vHTLX { get; set; }
        public string vHTZT { get; set; }
        public Nullable<int> iHTKSRQ { get; set; }
        public Nullable<int> iHTJSRQ { get; set; }
        public Nullable<decimal> mZJE { get; set; }
        public Nullable<int> iHTQDRQ { get; set; }
        public string vDH { get; set; }
        public string vCZ { get; set; }
        public string nDZ { get; set; }
        public Nullable<int> iYJJFRQ { get; set; }
        public string vFKFS { get; set; }
        public Nullable<int> iFKQS { get; set; }
        public string vJFFZR { get; set; }
        public string vQDYG { get; set; }
        public string nFJURL { get; set; }
        public string cSFTGSH { get; set; }
        public string cIsRemove { get; set; }
        public string nMemo { get; set; }
        public Nullable<System.DateTime> dInsTime { get; set; }
        public string vInsUser { get; set; }
        public Nullable<System.DateTime> dUpdTime { get; set; }
        public string vUpdUser { get; set; }
        public string nYFFZR { get; set; }
        public string nBohuiYY { get; set; }
        public string nHTName { get; set; }
    }
}
