//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_JXSLXR
    {
        public int iLXRID { get; set; }
        public string vLXRCode { get; set; }
        public string vJXScode { get; set; }
        public string nLXRMC { get; set; }
        public string nLXRYWM { get; set; }
        public string vLXDH1 { get; set; }
        public string vLXDH2 { get; set; }
        public string vFJH { get; set; }
        public string vYX { get; set; }
        public string vQQ { get; set; }
        public string vMSN { get; set; }
        public string vWB { get; set; }
        public Nullable<int> iSR { get; set; }
        public string vLXRZW { get; set; }
        public string nLXRDZ { get; set; }
        public string nJG { get; set; }
        public string nAH { get; set; }
        public string cIsRemove { get; set; }
        public string nBM { get; set; }
        public string nMemo { get; set; }
        public Nullable<System.DateTime> dInsTime { get; set; }
        public string vInsUser { get; set; }
        public Nullable<System.DateTime> dUpdTime { get; set; }
        public string vUpdUser { get; set; }
    }
}
