//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_JXSFK
    {
        public int iFKID { get; set; }
        public string vFKCode { get; set; }
        public string vJXSHTCode { get; set; }
        public Nullable<int> iYFRQ { get; set; }
        public Nullable<int> iSJFKRQ { get; set; }
        public Nullable<int> iFKQS { get; set; }
        public Nullable<decimal> dFKBFB { get; set; }
        public Nullable<decimal> mYF { get; set; }
        public Nullable<decimal> mYiF { get; set; }
        public Nullable<decimal> mWF { get; set; }
        public string nMemo { get; set; }
        public string vInsUser { get; set; }
        public Nullable<System.DateTime> dInsTime { get; set; }
        public string vUpdUser { get; set; }
        public Nullable<System.DateTime> dUpdTime { get; set; }
        public string cIsRemove { get; set; }
    }
}
