//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_KCGL
    {
        public int IID { get; set; }
        public string CpCode { get; set; }
        public string CpName { get; set; }
        public string Cplx { get; set; }
        public Nullable<int> RkSl { get; set; }
        public string CpDw { get; set; }
        public Nullable<System.DateTime> RkTime { get; set; }
        public string RkrName { get; set; }
        public string RkWz { get; set; }
        public string RkSm { get; set; }
        public Nullable<int> biaoshi1 { get; set; }
        public Nullable<int> cIsRemove { get; set; }
    }
}
