//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_KH
    {
        public int iKHID { get; set; }
        public string vKHCode { get; set; }
        public string nKHMC { get; set; }
        public string vQY { get; set; }
        public string vCS { get; set; }
        public string vSSXS { get; set; }
        public string nDZ1 { get; set; }
        public string nDZ2 { get; set; }
        public string vDH1 { get; set; }
        public string vDH2 { get; set; }
        public string vSSHY { get; set; }
        public string vKHLX { get; set; }
        public string vKHJB { get; set; }
        public string vKHLY { get; set; }
        public string vGSGM { get; set; }
        public string vKHZT { get; set; }
        public string vKHZH { get; set; }
        public string nKHYH { get; set; }
        public string vNSRSBH { get; set; }
        public string vCZ1 { get; set; }
        public string vCZ2 { get; set; }
        public string vWZ { get; set; }
        public string nMemo { get; set; }
        public string vInsUser { get; set; }
        public Nullable<System.DateTime> dInsTime { get; set; }
        public string vUpdUser { get; set; }
        public Nullable<System.DateTime> dUpdTime { get; set; }
        public string cIsRemove { get; set; }
        public string vJX { get; set; }
    }
}
