//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Publish_Project
    {
        public int iID { get; set; }
        public string ProjectCode { get; set; }
        public string ProjectName { get; set; }
        public Nullable<System.DateTime> ProjectDatetime { get; set; }
        public string ProjectWeb { get; set; }
        public string nMemo { get; set; }
        public Nullable<int> iFiled1 { get; set; }
        public Nullable<int> iFiled2 { get; set; }
        public Nullable<int> iFiled3 { get; set; }
        public string nFiled4 { get; set; }
        public string nFiled5 { get; set; }
        public string nFiled6 { get; set; }
        public string vFiled7 { get; set; }
        public string vFiled8 { get; set; }
        public Nullable<System.DateTime> dtFiled9 { get; set; }
        public Nullable<System.DateTime> dtFiled10 { get; set; }
        public string vInsUser { get; set; }
        public Nullable<System.DateTime> dInsTime { get; set; }
        public string vUpdUser { get; set; }
        public Nullable<System.DateTime> dUpdTime { get; set; }
    }
}
