//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_YG
    {
        public int iYGID { get; set; }
        public string vYGCode { get; set; }
        public string QXCode { get; set; }
        public string nDLID { get; set; }
        public string nMM { get; set; }
        public string nYGMC { get; set; }
        public string nYGYWMC { get; set; }
        public string cXB { get; set; }
        public string vSSJS { get; set; }
        public string vSSBM { get; set; }
        public string vSJLD { get; set; }
        public string vYX { get; set; }
        public string vDH1 { get; set; }
        public string vDH2 { get; set; }
        public string vSJ1 { get; set; }
        public string vSJ2 { get; set; }
        public string vQQ { get; set; }
        public string vMSN { get; set; }
        public Nullable<int> iRZSJ { get; set; }
        public Nullable<int> iLZSJ { get; set; }
        public Nullable<int> iSR { get; set; }
        public string vSFZH { get; set; }
        public string vKQBH { get; set; }
        public string vZXID { get; set; }
        public string cIsRemove { get; set; }
        public string nMemo { get; set; }
        public Nullable<System.DateTime> dInsTime { get; set; }
        public string vInsUser { get; set; }
        public Nullable<System.DateTime> dUpdTime { get; set; }
        public string vUpdUser { get; set; }
        public string vRoleCode { get; set; }
        public Nullable<int> iVIP { get; set; }
        public string vFirstName { get; set; }
        public string vLastName { get; set; }
        public string vHZYWMC { get; set; }
        public string iHeadCount { get; set; }
        public string vGS { get; set; }
        public string vGZCS { get; set; }
        public string vXZFFD { get; set; }
        public string vBMEN { get; set; }
        public string vBMCN { get; set; }
        public string vGWEN { get; set; }
        public string vGWCN { get; set; }
        public string vZWJB { get; set; }
        public string vZNZG1 { get; set; }
        public string vSecondZG { get; set; }
        public string vThirdZG { get; set; }
        public string vFourthZG { get; set; }
        public string vXXJL1 { get; set; }
        public Nullable<System.DateTime> dtGSRZSJ { get; set; }
        public Nullable<System.DateTime> dtJTRZSJ { get; set; }
        public string nYGSX { get; set; }
        public string nEmployeeBrand { get; set; }
        public string nGH { get; set; }
    }
}
