//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_ZPGL
    {
        public int IID { get; set; }
        public string ZprName { get; set; }
        public Nullable<int> Sex { get; set; }
        public Nullable<int> Age { get; set; }
        public string Phone { get; set; }
        public string Mail { get; set; }
        public string ZprXl { get; set; }
        public string WrokJy { get; set; }
        public string ZprZyzt { get; set; }
        public string ZprQrgzgw { get; set; }
        public string ZprQgsmc { get; set; }
        public Nullable<System.DateTime> MsTime { get; set; }
        public string MsgName { get; set; }
        public string MsGw { get; set; }
        public string MsJg { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> MialTime { get; set; }
        public string cIsRemover { get; set; }
    }
}
