//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AgentEventLog> AgentEventLogs { get; set; }
        public DbSet<AgentGroupInfo> AgentGroupInfoes { get; set; }
        public DbSet<AgentInfo> AgentInfoes { get; set; }
        public DbSet<AgentPilotNoLog> AgentPilotNoLogs { get; set; }
        public DbSet<AgentStatusLog> AgentStatusLogs { get; set; }
        public DbSet<Answer_Entity> Answer_Entity { get; set; }
        public DbSet<B_Business> B_Business { get; set; }
        public DbSet<B_Business_Compete> B_Business_Compete { get; set; }
        public DbSet<BasicData> BasicDatas { get; set; }
        public DbSet<C_Call_Record> C_Call_Record { get; set; }
        public DbSet<C_PersonContact> C_PersonContact { get; set; }
        public DbSet<CollectSet> CollectSets { get; set; }
        public DbSet<CRMEmil> CRMEmils { get; set; }
        public DbSet<DeviceEventLog> DeviceEventLogs { get; set; }
        public DbSet<DeviceStatu> DeviceStatus { get; set; }
        public DbSet<EmailSender> EmailSenders { get; set; }
        public DbSet<ibDeviceGroupStatistic> ibDeviceGroupStatistics { get; set; }
        public DbSet<Invert_Main> Invert_Main { get; set; }
        public DbSet<Invert_Main_Preview> Invert_Main_Preview { get; set; }
        public DbSet<K_City> K_City { get; set; }
        public DbSet<K_Knowledge_Info> K_Knowledge_Info { get; set; }
        public DbSet<K_Knowledge_Record> K_Knowledge_Record { get; set; }
        public DbSet<K_Role> K_Role { get; set; }
        public DbSet<K_Role_Info> K_Role_Info { get; set; }
        public DbSet<LimitSet> LimitSets { get; set; }
        public DbSet<ListName> ListNames { get; set; }
        public DbSet<Lxrbyzd> Lxrbyzds { get; set; }
        public DbSet<M_BM> M_BM { get; set; }
        public DbSet<M_CKGL> M_CKGL { get; set; }
        public DbSet<M_Color> M_Color { get; set; }
        public DbSet<M_CP> M_CP { get; set; }
        public DbSet<M_CPMC> M_CPMC { get; set; }
        public DbSet<M_CS> M_CS { get; set; }
        public DbSet<M_Customer> M_Customer { get; set; }
        public DbSet<M_FWXMMX> M_FWXMMX { get; set; }
        public DbSet<M_FWXXMX> M_FWXXMX { get; set; }
        public DbSet<M_GYS> M_GYS { get; set; }
        public DbSet<M_GYSBF_HY> M_GYSBF_HY { get; set; }
        public DbSet<M_GYSBJ> M_GYSBJ { get; set; }
        public DbSet<M_GYSFK> M_GYSFK { get; set; }
        public DbSet<M_GYSHT> M_GYSHT { get; set; }
        public DbSet<M_GYSHTCP> M_GYSHTCP { get; set; }
        public DbSet<M_GYSLXR> M_GYSLXR { get; set; }
        public DbSet<M_JS> M_JS { get; set; }
        public DbSet<M_JXS> M_JXS { get; set; }
        public DbSet<M_JXSBF> M_JXSBF { get; set; }
        public DbSet<M_JXSBJ> M_JXSBJ { get; set; }
        public DbSet<M_JXSFK> M_JXSFK { get; set; }
        public DbSet<M_JXSHT> M_JXSHT { get; set; }
        public DbSet<M_JXSHTCP> M_JXSHTCP { get; set; }
        public DbSet<M_JXSHTFW> M_JXSHTFW { get; set; }
        public DbSet<M_JXSLXR> M_JXSLXR { get; set; }
        public DbSet<M_JZDS> M_JZDS { get; set; }
        public DbSet<M_KCGL> M_KCGL { get; set; }
        public DbSet<M_KH> M_KH { get; set; }
        public DbSet<M_KHBF_HY> M_KHBF_HY { get; set; }
        public DbSet<M_KHBJ> M_KHBJ { get; set; }
        public DbSet<M_KHBZ> M_KHBZ { get; set; }
        public DbSet<M_KHFK> M_KHFK { get; set; }
        public DbSet<M_KHHJ> M_KHHJ { get; set; }
        public DbSet<M_KHHT> M_KHHT { get; set; }
        public DbSet<M_KHHTCP> M_KHHTCP { get; set; }
        public DbSet<M_KHHTFW> M_KHHTFW { get; set; }
        public DbSet<M_KHLLJL> M_KHLLJL { get; set; }
        public DbSet<M_KHLXR> M_KHLXR { get; set; }
        public DbSet<M_Publish_Project> M_Publish_Project { get; set; }
        public DbSet<M_Publish_Project_Detail> M_Publish_Project_Detail { get; set; }
        public DbSet<M_QY> M_QY { get; set; }
        public DbSet<M_SFZLXR> M_SFZLXR { get; set; }
        public DbSet<M_SJZD> M_SJZD { get; set; }
        public DbSet<M_YG> M_YG { get; set; }
        public DbSet<M_ZDPZ> M_ZDPZ { get; set; }
        public DbSet<M_ZPGL> M_ZPGL { get; set; }
        public DbSet<ModuleRunStatu> ModuleRunStatus { get; set; }
        public DbSet<Option_Entity> Option_Entity { get; set; }
        public DbSet<Option_Entity_Preview> Option_Entity_Preview { get; set; }
        public DbSet<Option_Q_Entity> Option_Q_Entity { get; set; }
        public DbSet<Q_Answer> Q_Answer { get; set; }
        public DbSet<Q_Entity> Q_Entity { get; set; }
        public DbSet<Q_Entity_Preview> Q_Entity_Preview { get; set; }
        public DbSet<QC_Answer> QC_Answer { get; set; }
        public DbSet<QC_Entity> QC_Entity { get; set; }
        public DbSet<RecDiskBak> RecDiskBaks { get; set; }
        public DbSet<RecIDCreater> RecIDCreaters { get; set; }
        public DbSet<RecManager> RecManagers { get; set; }
        public DbSet<Record_Info> Record_Info { get; set; }
        public DbSet<RecTable> RecTables { get; set; }
        public DbSet<S_Config> S_Config { get; set; }
        public DbSet<S_Seq_Log> S_Seq_Log { get; set; }
        public DbSet<S_Seq_Rule> S_Seq_Rule { get; set; }
        public DbSet<sock_Log> sock_Log { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<T_Allocation> T_Allocation { get; set; }
        public DbSet<T_ATTACH> T_ATTACH { get; set; }
        public DbSet<T_BLACK_LIST> T_BLACK_LIST { get; set; }
        public DbSet<T_Calerdar> T_Calerdar { get; set; }
        public DbSet<T_CalerdarPhone> T_CalerdarPhone { get; set; }
        public DbSet<t_callee_msg> t_callee_msg { get; set; }
        public DbSet<T_CalSwitch> T_CalSwitch { get; set; }
        public DbSet<T_CH> T_CH { get; set; }
        public DbSet<T_Const_Calendar_Rule> T_Const_Calendar_Rule { get; set; }
        public DbSet<T_ContactInfo> T_ContactInfo { get; set; }
        public DbSet<T_Emptcl> T_Emptcl { get; set; }
        public DbSet<T_FORM> T_FORM { get; set; }
        public DbSet<T_Front_USER> T_Front_USER { get; set; }
        public DbSet<T_FWHZ> T_FWHZ { get; set; }
        public DbSet<T_GYSFH> T_GYSFH { get; set; }
        public DbSet<T_HTZXQK> T_HTZXQK { get; set; }
        public DbSet<T_ImagePath> T_ImagePath { get; set; }
        public DbSet<T_InspectionData> T_InspectionData { get; set; }
        public DbSet<T_InspectionTask> T_InspectionTask { get; set; }
        public DbSet<t_investigation> t_investigation { get; set; }
        public DbSet<t_ivr_call_history> t_ivr_call_history { get; set; }
        public DbSet<t_ivr_out> t_ivr_out { get; set; }
        public DbSet<T_JXSFP_SH> T_JXSFP_SH { get; set; }
        public DbSet<T_KHFP> T_KHFP { get; set; }
        public DbSet<T_LIBRARY> T_LIBRARY { get; set; }
        public DbSet<T_MAIL> T_MAIL { get; set; }
        public DbSet<T_MAIL_ATTACHMENT> T_MAIL_ATTACHMENT { get; set; }
        public DbSet<T_Msg> T_Msg { get; set; }
        public DbSet<T_OT> T_OT { get; set; }
        public DbSet<T_PAGE> T_PAGE { get; set; }
        public DbSet<T_PAGE1> T_PAGE1 { get; set; }
        public DbSet<T_QC_pool> T_QC_pool { get; set; }
        public DbSet<T_RECORD_DETAIL> T_RECORD_DETAIL { get; set; }
        public DbSet<T_REFUND> T_REFUND { get; set; }
        public DbSet<T_RK> T_RK { get; set; }
        public DbSet<T_ROLE> T_ROLE { get; set; }
        public DbSet<T_ROLE_ACCESS> T_ROLE_ACCESS { get; set; }
        public DbSet<T_ROLE_ACCESS_DETAIL> T_ROLE_ACCESS_DETAIL { get; set; }
        public DbSet<T_ROLE_CONFIGURE> T_ROLE_CONFIGURE { get; set; }
        public DbSet<T_Satisfy> T_Satisfy { get; set; }
        public DbSet<T_Statuschange> T_Statuschange { get; set; }
        public DbSet<T_SubmitMsgResp> T_SubmitMsgResp { get; set; }
        public DbSet<T_Telephone> T_Telephone { get; set; }
        public DbSet<T_Ticket> T_Ticket { get; set; }
        public DbSet<T_Ticket_Att> T_Ticket_Att { get; set; }
        public DbSet<T_Ticket_Detail> T_Ticket_Detail { get; set; }
        public DbSet<T_TimeConfig> T_TimeConfig { get; set; }
        public DbSet<T_USER> T_USER { get; set; }
        public DbSet<T_USER_DEP> T_USER_DEP { get; set; }
        public DbSet<T_USER_ROLE> T_USER_ROLE { get; set; }
        public DbSet<T_YJZCGL> T_YJZCGL { get; set; }
        public DbSet<Task_Dial> Task_Dial { get; set; }
        public DbSet<Task_Dial_Agent> Task_Dial_Agent { get; set; }
        public DbSet<Task_Dial_Agent_Temp> Task_Dial_Agent_Temp { get; set; }
        public DbSet<Task_Dial_Cus> Task_Dial_Cus { get; set; }
        public DbSet<Task_Dial_Cus_Temp> Task_Dial_Cus_Temp { get; set; }
        public DbSet<Task_Dial_Temp> Task_Dial_Temp { get; set; }
        public DbSet<Test> Tests { get; set; }
        public DbSet<test_num> test_num { get; set; }
        public DbSet<TrunkEventLog> TrunkEventLogs { get; set; }
        public DbSet<TrunkStatistic> TrunkStatistics { get; set; }
        public DbSet<TrunkStatu> TrunkStatus { get; set; }
        public DbSet<VDNLog> VDNLogs { get; set; }
        public DbSet<VDNStat> VDNStats { get; set; }
    }
}
