//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecTable
    {
        public decimal RecID { get; set; }
        public string CTID { get; set; }
        public string RecFileName { get; set; }
        public string ChnlNo { get; set; }
        public Nullable<System.DateTime> BeginTime { get; set; }
        public Nullable<int> TimeSpan { get; set; }
        public Nullable<int> FileSize { get; set; }
        public string Caller { get; set; }
        public string Callee { get; set; }
        public string AgentID { get; set; }
        public string AgentName { get; set; }
        public string RecMemo { get; set; }
        public string FilePath { get; set; }
        public string BakFlag { get; set; }
        public string BakDiskID { get; set; }
        public string TrunkConnectPhoneNo { get; set; }
        public string DevPhoneNo { get; set; }
        public string host { get; set; }
        public string backupflag { get; set; }
    }
}
