//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Calerdar
    {
        public int Auto_ID { get; set; }
        public Nullable<System.DateTime> I_Date { get; set; }
        public Nullable<int> is_on_duty { get; set; }
        public string off_duty_transfer { get; set; }
        public string Memo { get; set; }
        public string Create_User { get; set; }
        public Nullable<System.DateTime> Create_Time { get; set; }
        public string Update_User { get; set; }
        public Nullable<System.DateTime> Update_Time { get; set; }
    }
}
