//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CH
    {
        public int iID { get; set; }
        public string vCPCode { get; set; }
        public string vHTCode { get; set; }
        public string cCHRCode { get; set; }
        public Nullable<decimal> mCKDJ { get; set; }
        public Nullable<int> mCKSL { get; set; }
        public Nullable<decimal> mCKZJ { get; set; }
        public Nullable<int> iCKRQ { get; set; }
        public string cHTCH { get; set; }
        public string vQSR { get; set; }
        public Nullable<int> iQSRQ { get; set; }
        public string vKDGSCode { get; set; }
        public string nKDDH { get; set; }
        public Nullable<decimal> mKDF { get; set; }
        public Nullable<int> iKC { get; set; }
        public string nFJURL { get; set; }
        public string nMemo { get; set; }
        public string cIsRemove { get; set; }
        public string vInsUser { get; set; }
        public Nullable<System.DateTime> dInsTime { get; set; }
        public string vUpdUser { get; set; }
        public Nullable<System.DateTime> dUpdTime { get; set; }
    }
}
