//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Emptcl
    {
        public int ID { get; set; }
        public string AccountName { get; set; }
        public string AccountId { get; set; }
        public string ServiceId { get; set; }
        public string Password { get; set; }
        public string IPAddress { get; set; }
        public string Port { get; set; }
    }
}
