//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_FWHZ
    {
        public int iID { get; set; }
        public string vFWBH { get; set; }
        public string cFWJG { get; set; }
        public string cJXPG { get; set; }
        public Nullable<int> iXCPGSJ { get; set; }
        public string nWWCYY { get; set; }
        public string nFWRYBZ { get; set; }
        public Nullable<System.DateTime> dXYSJ { get; set; }
        public string cFWTD { get; set; }
        public string cGTNL { get; set; }
        public string nKHBZ { get; set; }
        public string nFJURL { get; set; }
        public Nullable<System.DateTime> dSJDDSJ { get; set; }
        public string nMemo { get; set; }
        public string vInsUser { get; set; }
        public Nullable<System.DateTime> dInsTime { get; set; }
        public string vUpdUser { get; set; }
        public Nullable<System.DateTime> dUpdTime { get; set; }
        public string cIsRemove { get; set; }
    }
}
