//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_HTZXQK
    {
        public int iID { get; set; }
        public string vHTCode { get; set; }
        public string vZXLX { get; set; }
        public string cYYDJ { get; set; }
        public string vDJLX { get; set; }
        public string vDJBH { get; set; }
        public Nullable<System.DateTime> dZXSJ { get; set; }
        public string vFZR { get; set; }
        public string nFJURL { get; set; }
        public string nMemo { get; set; }
        public string cIsRemove { get; set; }
        public string vInsUser { get; set; }
        public Nullable<System.DateTime> dInsTime { get; set; }
        public string vUpdUser { get; set; }
        public Nullable<System.DateTime> dUpdTime { get; set; }
    }
}
