//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_RK
    {
        public int iID { get; set; }
        public string vCPCode { get; set; }
        public Nullable<int> iQSRQ { get; set; }
        public string vQSR { get; set; }
        public Nullable<int> vDJLX { get; set; }
        public Nullable<decimal> mRKDJ { get; set; }
        public Nullable<decimal> mRKZJ { get; set; }
        public string nMemo { get; set; }
        public string cIsRemove { get; set; }
        public string vInsUser { get; set; }
        public Nullable<System.DateTime> dInsTime { get; set; }
        public string vUpdUser { get; set; }
        public Nullable<System.DateTime> dUpdTime { get; set; }
    }
}
